### PR TITLE
Clarified the # of texture units in WebGL

### PR DESCRIPTION
**Pull request by adkelley**

### CODE REVIEW

**Comment by greggman** [comment]
Unless there's something new I missed it seems like it was correct before. WebGL2 has a minimum of 16, it can have more. To put it another way you can make a WebGL2 page that uses 16 texture units and it should run everywhere that runs WebGL2. You can also make an app that uses 17 texture units. That will only run on devices where WebGL2 supports more than the minimum 16 (and you should therefore query the number to texture units)

**Comment by adkelley** [comment]
I see.  Your explanation helped to clarify it for me, thank you. There's not much info on WebGL2 texture units on the web, so I suggest amending that paragraph with your clarification.   Thanks again!

**Comment by greggman** [comment]
So I tweak the wording a little. I hope it's ok.

Maybe I should make another chapter on WebGL2's limits.

**Comment by adkelley** [comment]
Nice!  My latest pull request is simply a grammar correction to your new sentence.

**Comment by greggman** [comment]
I think this is update to date.

**Pull request closed without merging**
